#!/bin/bash

basefolder="./vendor/bigpoint/slim-bootstrap/generator/skeleton/"

if [ $# -ne 1 ]; then
    echo "Usage: $0 <namespace>"
    exit 1
fi

namespace="$1"
namespace_lower="$(echo ${namespace} | tr '[:upper:]' '[:lower:]' | sed 's:\\:-:g')"
namespace_folder="$(echo ${namespace} | sed 's:\\:/:g')"
namespace="$(echo ${namespace} | sed 's:\\:\\\\:g')"

echo -e "\e[1mGenerating skeleton for \e[34m${namespace}\e[1;39m ...\e[0m"

for template in $(find "${basefolder}" -type f -not -name ".lock"); do
    file=${template//${basefolder}/}
    file=$(echo ${file} | sed "s:###NAMESPACE###:${namespace_folder}:")
    file="./${file}"

    echo "creating ${file} from ${template} ..."

    dir="$(dirname "${file}")"

    mkdir -p "${dir}"

    sed "s:###NAMESPACE###:${namespace}:g" "${template}" > "${file}"
    sed -i -e "s:###NAMESPACE_LOWER###:${namespace_lower}:g" "${file}"
done

for directory in $(find "${basefolder}" -type f -name ".lock"); do
    directory="$(dirname ${directory})"
    directory=${directory//${basefolder}/}

    mkdir -pv "${directory}"
done
